// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-16 Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow
{
    using System;
    using System.Runtime.InteropServices;

    using Audio;
    using Diagnostics;
    using Graphics;
    using Interop;

    /// <content>
    /// Contains code pertaining to C++ interop.
    /// </content>
    public sealed partial class Program
    {
        /// <summary>
        /// Initializes all Rainbow components on startup.
        /// </summary>
        /// <param name="masterTablePtr">Pointer to the master table of functions.</param>
        internal static void InitializeComponents(IntPtr masterTablePtr)
        {
            var masterTable = Marshal.PtrToStructure<UMaster>(masterTablePtr);
            Assert.Equal(masterTable.SizeOfStruct, Marshal.SizeOf(masterTable));

            Animation.InitializeComponents(masterTable.Animation);
            FontAtlas.InitializeComponents(masterTable.FontAtlas);
            Label.InitializeComponents(masterTable.Label);
            SceneNode.InitializeComponents(masterTable.SceneNode);
            Sprite.InitializeComponents(masterTable.Sprite);
            SpriteBatch.InitializeComponents(masterTable.SpriteBatch);
            TextureAtlas.InitializeComponents(masterTable.TextureAtlas);
            Mixer.InitializeComponents(masterTable.Mixer);
            Sound.InitializeComponents(masterTable.Sound);

            SceneNode.SetRootNode(masterTable.RootNode);
        }
    }
}
