// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-16 Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

namespace Rainbow.Interop
{
    using System;
    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential)]
    internal sealed class UMaster
    {
        private readonly uint sizeOfStruct;
        private readonly IntPtr rootNode;
        private readonly IntPtr animation;
        private readonly IntPtr fontAtlas;
        private readonly IntPtr label;
        private readonly IntPtr sceneNode;
        private readonly IntPtr sprite;
        private readonly IntPtr spriteBatch;
        private readonly IntPtr textureAtlas;
        private readonly IntPtr mixer;
        private readonly IntPtr sound;

        public uint SizeOfStruct => sizeOfStruct;

        public IntPtr RootNode => rootNode;

        public IntPtr Animation => animation;

        public IntPtr FontAtlas => fontAtlas;

        public IntPtr Label => label;

        public IntPtr SceneNode => sceneNode;

        public IntPtr Sprite => sprite;

        public IntPtr SpriteBatch => spriteBatch;

        public IntPtr TextureAtlas => textureAtlas;

        public IntPtr Mixer => mixer;

        public IntPtr Sound => sound;
    }
}
