// This file was generated by Rainbow for .NET Core. Do not modify.
//
// Copyright (c) 2010-16 Bifrost Entertainment AS and Tommy Nguyen
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)

#ifndef DOTNET_RAINBOW_INTEROP_UMASTER_H_
#define DOTNET_RAINBOW_INTEROP_UMASTER_H_

#include "DotNet/Rainbow/Interop/Audio/UMixer.h"
#include "DotNet/Rainbow/Interop/Audio/USound.h"
#include "DotNet/Rainbow/Interop/Graphics/UAnimation.h"
#include "DotNet/Rainbow/Interop/Graphics/UFontAtlas.h"
#include "DotNet/Rainbow/Interop/Graphics/ULabel.h"
#include "DotNet/Rainbow/Interop/Graphics/USceneNode.h"
#include "DotNet/Rainbow/Interop/Graphics/USprite.h"
#include "DotNet/Rainbow/Interop/Graphics/USpriteBatch.h"
#include "DotNet/Rainbow/Interop/Graphics/UTextureAtlas.h"

namespace rainbow
{
    struct UMaster
    {
        uint32_t size_of_struct = sizeof(UMaster);
        SceneNode* root_node;
        UAnimation* animation;
        UFontAtlas* font_atlas;
        ULabel* label;
        USceneNode* scene_node;
        USprite* sprite;
        USpriteBatch* sprite_batch;
        UTextureAtlas* texture_atlas;
        UMixer* mixer;
        USound* sound;
    };

    inline void initialize_components(SceneNode& root_node,
                                      void (*initialize_components)(void*))
    {
        UAnimation animation;
        UFontAtlas font_atlas;
        ULabel label;
        USceneNode scene_node;
        USprite sprite;
        USpriteBatch sprite_batch;
        UTextureAtlas texture_atlas;
        UMixer mixer;
        USound sound;

        UMaster master;
        master.root_node = &root_node;
        master.animation = &animation;
        master.font_atlas = &font_atlas;
        master.label = &label;
        master.scene_node = &scene_node;
        master.sprite = &sprite;
        master.sprite_batch = &sprite_batch;
        master.texture_atlas = &texture_atlas;
        master.mixer = &mixer;
        master.sound = &sound;

        initialize_components(&master);
    }
}

#endif
